[package]
name = "catalyst"
version = "0.1.0"
authors = ["aaronhyperum <unysnhyperum@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.16.2"

[dependencies]
lalrpop-util = "0.16.2"
regex = "0.2.1"